### ISSUE TITLE
挂着，隔几个小时在看就终止了

### ISSUE THREAD

**Issue by flless8** [Afool4U/MIGPT#10]
<img width="859" alt="image" src="https://github.com/Afool4U/MIGPT/assets/64878354/abdf9efa-c65a-4613-8a70-38b1f34ff711">

**Comment by Dylan-Li8** [comment]
可以用修改的版本，已解决这个问题。
https://github.com/Dylan-Li8/MIGPT

**Comment by flless8** [comment]
好的

**Comment by Dylan-Li8** [comment]
只是我将v3.py文件里的地址改成了openai-sb.com的地址，如果你是官方API，需要自己改回来。

**Comment by flless8** [comment]
了解，谢提醒，正准备弄
