### ISSUE TITLE
get_latest_ask_from_xiaoai   这句会不会因为太频繁 被封啊

### ISSUE THREAD

**Issue by 6313504** [Afool4U/MIGPT#16]
get_latest_ask_from_xiaoai   这句会不会因为太频繁 被封啊

**Comment by Afool4U** [comment]
会的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月5日(周日) 晚上10:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Afool4U/MIGPT] get_latest_ask_from_xiaoai   这句会不会因为太频繁 被封啊 (Issue #16)




 
get_latest_ask_from_xiaoai   这句会不会因为太频繁 被封啊
